In [ ]:
# XGBoosting.com
# Fit an XGBoost Model for Binary Classification using scikit-learn API
from sklearn.datasets import make_classification
from xgboost import XGBClassifier

# Generate a synthetic dataset with 2 classes
X, y = make_classification(n_samples=1000, n_features=20, n_informative=2, n_redundant=10, random_state=42)



In [ ]:
X, y

(array([[-0.49693203, -0.33912228,  0.22914552, ..., -1.17927302,
          0.45780561,  0.35600629],
        [ 0.01249932,  1.00744397,  0.14009566, ..., -1.76385344,
          0.93791554,  0.45936344],
        [-0.72021202, -1.24448645, -0.47229097, ...,  0.41394755,
         -0.5387903 , -0.26636053],
        ...,
        [ 1.01027459, -0.13092581,  1.18030384, ..., -1.98959095,
         -0.80579965,  0.88702644],
        [-1.20775939, -0.3807634 ,  0.12906749, ..., -0.77725344,
          0.59910333,  0.22671772],
        [ 1.14356604, -0.42459817, -0.31394763, ...,  1.24769039,
         -0.30704834, -0.40246308]]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
   

In [ ]:
# Initialize XGBClassifier
model = XGBClassifier(objective='binary:logistic', random_state=42)

# Fit the model to training data
model.fit(X, y)

# Make predictions with the fit model
predictions = model.predict(X)
print(predictions[:5])

In [ ]:
import torch
from transformers import BertTokenizer,BertModel

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# models: https://huggingface.co/models?sort=downloads


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
def get_embeddings(sentence):
  T=160
  tokens = tokenizer.tokenize(sentence)
  padded_tokens = tokens + ['[PAD]' for _ in range(T-len(tokens))]
  # print("Padded tokens are \n {} ".format(padded_tokens))
  sent_ids = tokenizer.convert_tokens_to_ids(padded_tokens)
  token_ids = torch.tensor(sent_ids).unsqueeze(0)
  return token_ids

In [ ]:
import pandas as pd
df_train = pd.read_csv('/content/sample_data/train.csv')
df_train['tensors'] = df_train["text"].apply(lambda x : get_embeddings(x))
df_train.sample(n=30)

id            keyword                   location  \
1166   1679  bridge%20collapse                        NaN   
1021   1483        body%20bags                        NaN   
2811   4043           disaster                       USA    
6795   9734            tragedy                     Canada   
1758   2530          collision  Orange County, California   
7344  10516           wildfire           Washington State   
4682   6656          landslide                Roanoke, VA   
449     652             attack                   Location   
6012   8585            screams              United States   
577     835          bioterror                        NaN   
263     380       annihilation                Phoenix, AZ   
2280   3274           demolish                 Fruit Bowl   
5925   8458           screamed                        NaN   
5966   8517          screaming            Namjoon's pants   
1584   2286       cliff%20fall                        NaN   
2486   3569           desolate  ÌÏT: 33.209923,-87.545328   
1030   1495        body%20bags             United Kingdom   
2172   3115             debris                        NaN   
3031   4352         earthquake                        NaN   
5581   7963              razed                  Tulsa, OK   
7017  10058            typhoon                        NaN   
4506   6404          hurricane       Books Published, USA   
2861   4112            drought                  Caribbean   
7553  10798            wrecked                        NaN   
5959   8510          screaming                        NaN   
6429   9194  suicide%20bombing                  Australia   
3445   4923           exploded                        NaN   
2567   3682            destroy                        NaN   
5439   7759             police                    Nigeria   
776    1123          blew%20up                        NaN   

                                                   text  target  \
1166  I never knew about the relationship btwn Kansa...       1   
1021  Child Shoulder Bags PVC Shoulder Book Bag Cart...       0   
2811  DISASTER AVERTED: Police kill gunman with ‰Û÷h...       0   
6795  DTN India: Rly tragedy in MP: Some live to rec...       1   
1758  Westminister Sr22 W / Knott St **Trfc Collisio...       1   
7344  Wildfire near Columbia River town is 50 percen...       1   
4682  LANDSLIDE (live) by FLEETWOOD MAC #nowplaying ...       0   
449   BREAKING: Terror Attack On\nPolice Post #Udhampur       1   
6012  @wisdc &amp; obama supports  death2USA .. http...       0   
577   Jacksonville Busines FedEx stops shipping pote...       1   
263   Hey #AZ: Sign this petition to save the #WildH...       0   
2280  @XGN_Infinity @Ronin_Carbon HAHAH Mutual host ...       0   
5925  I just got screamed at for asking my dad to mo...       0   
5966  '[+54 -9] How do people not know who Kendall J...       0   
1584  @SZMNextDoor I got this cute lil cliff you can...       0   
2486  If this ATL to San Fran flight goes down in a ...       0   
1030  Womens Buckle Casual Stylish Shoulder Handbags...       0   
2172  RÌ©union Debris Is Almost Surely From Flight 3...       1   
3031  Put the RIGHT person up on the block #Shelli??...       0   
5581  The Latest: More homes razed by Northern Calif...       1   
7017  #Breaking144 Obama Declares Disaster for Typho...       1   
4506  Hurricane Dancers: The First Caribbean Pirate ...       0   
2861  Heat wave is relentless:  91å¡F Feels Like 100...       1   
7553  #news Cramer: Iger's 3 words that wrecked Disn...       0   
5959  Harshness Follows Us a\nBetter Day\nby Sarah C...       0   
6429  @daisycuttertz @GROGParty @Tony_Burke He's bee...       1   
3445  My little heart just exploded #OTRAMETLIFE #MT...       0   
2567  Me and all my friends could destroy this in 2h...       0   
5439  Now Trending in Nigeria: Police charge traditi...       1   
776   Ye did the same thing to Big Sean and he still...       0   

                                       

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
X = df_train['tensors'].tolist()
X = np.array(X)
X = np.squeeze(X)
y = df_train['target'].tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Initialize XGBClassifier
model = XGBClassifier(objective='binary:logistic', random_state=42)

# Fit the model to training data
model.fit(X_train, y_train)

# Make predictions with the fit model
predictions = model.predict(X)
print(predictions[:5])

[0 1 1 1 1]


In [ ]:
sum(predictions == df_train['target'].to_numpy()) / len(predictions == df_train['target'].to_numpy()) * 100

92.21069223696308

7613